apigee/apigee-remote-service-envoy

- main.go
- samples/istio/hybrid-apigee-remote-service-envoy.yaml
- samples/istio/saas-apigee-remote-service-envoy.yaml
> made flags consistent

- .github/workflows/docker.yaml
> switch to docker hub

- server/authmanager.go
A NewToken function is factored out and exported along with the SignJWT one. Change is minimal.
> exporting two functions for cli to generate internal JWT

- go.mod
- go.sum
- server/accesslog_test.go
There is change of the manager interface in [issue-9](https://github.com/apigee/apigee-remote-service-golib/issues/9) of -golib repo. This is to address it.
> made test pass

- samples/istio/envoyfilter-sidecar-1.7.yaml
> add example for istio 1.7

- .github/workflows/docker.yaml
- Dockerfile
- Dockerfile_releaser
- go.mod
- samples/istio/hybrid-apigee-remote-service-envoy.yaml
- samples/istio/request-authentication.yaml
- samples/istio/saas-apigee-remote-service-envoy.yaml
update standard go to 1.15.0
update goboring to 1.14.6
closes #43 
closes #44
> non-root user for docker and k8s

- server/accesslog.go
- server/accesslog_test.go
> canceled requests may be missing response code

- main.go
- server/config.go
- server/config_test.go
> loading config CRDs in any order; print config upon starting as json

- main.go
- server/handler.go
- server/handler_test.go
> add clean shutdown hook

- main.go
- server/kube_health.go
- server/kube_health_test.go
> products must load before /healthz ready

- go.mod
- go.sum
> prerelease for 1.2.0

- server/config.go
- server/config_test.go
This mainly affected the CLI tool by printing extraneous stuff.
> Minor fix in config.Load()

- kokoro/README.md
- kokoro/gcp_ubuntu/continuous.cfg
- kokoro/gcp_ubuntu/kokoro_build.sh
- kokoro/scripts/integration_test.sh
Close #37 
The script does very little right now (it builds the image locally). But let's get this going first. Once everything works, both this repo and the -cli one will be polled and tested periodically.
> init kokoro

- main.go
- server/authmanager_test.go
- server/config.go
- server/config_test.go
- server/handler.go
- server/handler_test.go
- server/kube_health_test.go
> Support reading default application credentials for analytics uploading

- server/accesslog.go
- server/accesslog_test.go
> Improved `StreamAccessLog` service

- kokoro/gcp_ubuntu/kokoro_build.sh
- kokoro/scripts/init.sh
- kokoro/scripts/integration_test_cgsaas.sh
- kokoro/scripts/integration_test_hybrid.sh
> Workflow for tests with CG SaaS

- go.mod
- go.sum
- server/accesslog_test.go
- server/authorization.go
- server/authorization_test.go
- server/header_context_test.go
> OperationGroup support

- kokoro/scripts/integration_test_cgsaas.sh
- kokoro/scripts/integration_test_hybrid.sh
- kokoro/scripts/lib.sh
> cleaning up resources upon start

- server/config.go
- server/config_test.go
- server/handler_test.go
> analytics rollback

- kokoro/scripts/integration_test_cgsaas.sh
- kokoro/scripts/integration_test_hybrid.sh
- kokoro/scripts/lib.sh
- server/config.go
- server/config_test.go
> removed limit on number of resources read from config

- kokoro/scripts/integration_test_hybrid.sh
fixed the mistake introduced by #101
> removed the text mistakenly pasted

- kokoro/scripts/lib.sh
> removed --tag in envoy samples creation

- kokoro/gcp_ubuntu/continuous.cfg
- kokoro/gcp_ubuntu/kokoro_build.sh
- kokoro/scripts/integration_test_cgsaas.sh
- kokoro/scripts/integration_test_hybrid.sh
- kokoro/scripts/integration_test_opdk.sh
- kokoro/scripts/lib.sh
> Added OPDK integration build script

- kokoro/gcp_ubuntu/cgsaas.cfg
- kokoro/gcp_ubuntu/cgsaas_build.sh
- kokoro/gcp_ubuntu/common.cfg
- kokoro/gcp_ubuntu/hybrid.cfg
- kokoro/gcp_ubuntu/hybrid_build.sh
- kokoro/gcp_ubuntu/loadtest.cfg
- kokoro/gcp_ubuntu/loadtest_build.sh
- kokoro/gcp_ubuntu/opdk.cfg
- kokoro/gcp_ubuntu/opdk_build.sh
- kokoro/scripts/init.sh
- kokoro/scripts/integration_test_cgsaas.sh
- kokoro/scripts/integration_test_hybrid.sh
- kokoro/scripts/integration_test_opdk.sh
- kokoro/scripts/lib.sh
- kokoro/scripts/load_test.sh
> Separating Kokoro builds into four

- .github/workflows/docker.yaml
- Dockerfile_releaser
> update to goboring 1.15.5b5

- kokoro/scripts/integration_test_hybrid.sh
- kokoro/scripts/lib.sh
> increased JWT time skew; added empty request body to product revoke call

- .github/workflows/docker.yaml
> update github build-push-action

- .github/workflows/release.yaml
- Dockerfile_releaser
> allow goreleaser to work with multiple tags

- integration-test/payloads/application_prod.json
- integration-test/payloads/httpbin_product_prod.json
- integration-test/scripts/cgsaas_test.sh
- integration-test/scripts/hybrid_lib.sh
- integration-test/scripts/hybrid_test.sh
- integration-test/scripts/init.sh
- integration-test/scripts/legacy_lib.sh
- integration-test/scripts/load_test.sh
- integration-test/scripts/opdk_test.sh
- integration-test/scripts/test_lib.sh
- integration-test/scripts/util_lib.sh
Added multi-env test with local Envoy
Largely refactored the bash scripts.
fix #141
NOTE: It doesn't seem straightforward to configure the same thing using Istio EnvoyFilter CR on the Istio sidecar but I hope to get the Envoy test covered in nightly build first.
> Added multi-env test with local Envoy

- integration-test/scripts/cgsaas_test.sh
- integration-test/scripts/hybrid_lib.sh
- integration-test/scripts/hybrid_test.sh
- integration-test/scripts/opdk_test.sh
> added clean up of remote-token proxy

- go.mod
- go.sum
- server/accesslog_test.go
- server/authorization.go
- server/authorization_test.go
> log analytics record immediately when sending deny to Envoy

- server/authorization.go
- server/authorization_test.go
- server/config.go
- server/handler.go
- server/handler_test.go
> rename config reject_unauthorized to allow_unauthorized

- integration-test/scripts/test_lib.sh
> changed quota exhausted status code checking

- server/config.go
- server/config_test.go
- server/handler.go
> removed udca support in server config

- go.mod
- go.sum
- server/accesslog.go
- server/accesslog_test.go
- server/authorization_test.go
- server/handler.go
- server/metadata_context.go
> support data capture attributes from metadata

- server/authmanager.go
- server/config.go
Removed unnecessary code.
closes  #147
> remove deprecated call to x509.DecryptPEMBlock

- .github/workflows/docker.yaml
- Dockerfile
- Dockerfile_releaser
- integration-test/README.md
> goboring 1.16b7

- server/authorization.go
- server/authorization_test.go
> added request context support for target matching

- go.mod
- go.sum
- server/authorization.go
- server/authorization_test.go
- server/config.go
- server/config_test.go
- server/handler.go
- server/handler_test.go
- server/header_context.go
- server/header_context_test.go
- server/metadata_context.go
- server/metadata_context_test.go
> target replaced with api

- server/config.go
- server/config_test.go
- server/handler.go
- server/handler_test.go
> removed analytics.tls in config

- server/config_test.go
> update allConfigOptions to match config

- server/authorization.go
- server/authorization_test.go
> return error on incorrect apigee_environment metadata

- go.mod
- go.sum
- integration-test/scripts/cgsaas_test.sh
- server/handler.go
close #185
Added AuthRoundTripper call to the RoundTripper for analytics client without GCP credentials.
> fixed legacy saas analytics issue

- server/accesslog.go
- server/accesslog_test.go
- server/authorization_test.go
> removed ptypes dep

- go.mod
- go.sum
- server/config.go
- server/config_test.go
> replace go-multierror with errorset

- config/config_test.go
- config/env_config.go
- config/env_config_test.go
> remove as much dependencies as possible from env_config.go and its test file

- config/env_spec_request.go
- server/authorization.go
- server/authorization_test.go
> API base path must be stripped from request path

- config/config.go
> Add json tags to avoid private keys being printed

- server/authorization.go
- server/authorization_test.go
> more testing

- config/env_spec_request.go
- config/env_spec_request_test.go
- go.mod
- go.sum
- server/authorization.go
- server/authorization_test.go
> support ConsumerAuthorization.FailOpen

- config/env_spec.go
- config/env_spec_test.go
- server/authorization.go
- server/authorization_test.go
> append headers support both map and slice of key/values

- config/env_spec.go
- config/env_spec_test.go
close #237 
restriction on ID uniqueness is removed
> basepaths uniqueness within environment spec

- config/env_spec_ext.go
- config/env_spec_request.go
- server/authorization.go
- server/authorization_test.go
> add additional debug logging

- config/config.go
- config/config_test.go
- config/env_spec.go
- config/testdata/envspec/good_env_config.yaml
- config/testdata/good_config.yaml
- main.go
> read a list of files or directories for env spec

- config/env_spec_ext.go
- config/env_spec_ext_test.go
- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
- go.mod
- go.sum
- server/authorization_test.go
- server/handler.go
- transform/parser.go
- transform/parser_test.go
> implement StringTransform.Transform

- config/env_spec_ext.go
- config/env_spec_ext_test.go
- config/env_spec_test.go
> transform JWTAuthentication parameters

- config/env_spec_test.go
> make test less brittle

- server/authorization.go
- server/authorization_test.go
> header removes must be case-insensitive

- server/kube_health.go
- server/kube_health_test.go
> fix race conditions

- config/config.go
- config/config_test.go
- server/handler.go
> add OperationConfigType

- main.go
- server/accesslog.go
- server/accesslog_test.go
> fix accesslog timeout, close stream on term signal

- config/env_spec.go
- config/env_spec_request.go
- config/env_spec_request_test.go
> add disabled flag for authz

- config/env_spec.go
- config/env_spec_ext.go
- config/env_spec_test.go
- server/authorization_test.go
> validate method and match any

- config/config_test.go
- config/env_spec.go
- config/env_spec_ext.go
- config/env_spec_ext_test.go
- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
- server/authorization_test.go
> Fix JWTAuthentication maps. Resolve and validate the JWT requirement references in consumer authz.

- config/env_spec_ext.go
- config/env_spec_ext_test.go
- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
> operation with no matchers is a wildcard

- hcl_shim/hcl/printer/shim.go
- hcl_shim/shim.go
- server/authorization.go
- server/authorization_test.go
- server/handler.go
> strip base path off for proxy mode

- config/env_spec_request.go
- config/env_spec_request_test.go
- server/authorization.go
- server/authorization_test.go
ConsumerAuthorization missing or disabled should passthrough 
Fixes #278
> ConsumerAuthorization passthrough

- integration-test/scripts/cgsaas_test.sh
- integration-test/scripts/test_lib.sh
By default, read permission is not given in the test vm...
#229
> give container read permission to config files

- server/authorization.go
- server/authorization_test.go
> debug logging for header modifications

- server/accesslog_test.go
- server/authorization.go
- server/authorization_test.go
- server/handler.go
- server/kube_health.go
- server/kube_health_test.go
> return 503 from ext_auth until products loaded

- config/config.go
- go.mod
- go.sum
- server/handler.go
> gcp managed internal api will not be exclusive to AX credentials

- server/authorization.go
- server/authorization_test.go
> AX not sent on some rejections

- config/env_spec_request.go
- config/env_spec_test.go
> first match wins for authn http params

- config/env_spec.go
- config/env_spec_ext.go
- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
> fix auth disabled flags

- transform/parser.go
> fix lint issue of participle tags

- config/env_spec.go
- config/env_spec_test.go
> do not create one-of error when auth disabled

- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
- server/authorization_test.go
> check consumer auth disabled field

- go.mod
- go.sum
To reflect this: https://github.com/apigee/apigee-remote-service-golib/issues/92
> update to latest golib with jwx fetching error logs

- server/authorization.go
- server/authorization_test.go
> always strip basepath for envspec configs

- config/config_test.go
- config/env_spec.go
- config/env_spec_ext.go
- config/env_spec_ext_test.go
- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
- config/testdata/good_env_config.yaml
- server/authorization.go
- server/authorization_test.go
- testutil/envoy.go
- transform/parser.go
- transform/parser_test.go
> Implement http rewrites

- server/authorization.go
- server/authorization_test.go
> fix AX sending issue

- server/accesslog.go
- server/accesslog_test.go
- server/authorization.go
- server/authorization_test.go
> change gatewaysource in AX record

- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
- go.mod
- go.sum
> fix api basepath matching

- go.mod
- server/authorization.go
- server/authorization_test.go
- server/header_context.go
> Add Apigee Dynamic Data headers

- config/config_test.go
- config/env_spec.go
- config/env_spec_ext.go
- config/env_spec_request.go
- config/env_spec_request_test.go
- config/env_spec_test.go
- config/testdata/good_env_config.yaml
- server/authorization_test.go
The requestVariables type is changed to map[string]map[string]string.
> Add Namespace to ContextVariables. Refactor requestVariables.

- server/authorization.go
- server/authorization_test.go
> x-apigee fault headers on internal err only

- server/authmanager.go
- server/authmanager_test.go
> add nil-check for decoded private key pem bytes

- .github/workflows/build.yaml
> Update actions/checkout to v2

- Dockerfile_releaser
> Remove use of deprecated goreleaser.sh

- server/authorization.go
- server/header_context.go
- server/header_context_test.go
> log message ID header

- config/env_spec.go
- server/authorization.go
- server/authorization_test.go
> Remove x-apigee-* headers before sending to target

- fault/fault_codes.go
- server/authorization.go
- server/authorization_test.go
- server/header_context.go
- server/header_context_test.go
* Added a new code to better distinguish "api key not found" from
"api key not present."
Closes #378
> Update fault codes to better reflect config model.

- go.mod
- go.sum
> Updating to latest apigee-remote-service-golib

- config/env_spec.go
- config/env_spec_request.go
- server/accesslog.go
- server/accesslog_test.go
- server/authorization.go
- server/authorization_test.go
- server/metadata_context.go
- server/metadata_context_test.go
> allow setting dynamic metadata in env_spec

- .gitignore
- go.mod
- go.sum
- main.go
- server/accesslog.go
- server/authorization.go
- server/header_context.go
- server/header_context_test.go
- server/metadata_context.go
- server/metadata_context_test.go
> Add support for analytics for gRPC APIs

- go.mod
- go.sum
- server/authorization.go
Fixes #400
Need to update Golib version before this is complete.
> fix handling of errors for analytics
