go.mod
samples/istio/hybrid-apigee-remote-service-envoy.yaml

Now that the gcp managed proxies work with an http2 client ([issue-33](https://github.com/apigee/apigee-remote-service-cli/issues/33) in -cli repo), the GODEBUG env is removed from the related config.
Note: go.mod has been updated to use go version 1.14.

removed GODEBUG env in the hybrid sample config

---

go.mod
go.sum
main.go
server/accesslog.go
server/accesslog_test.go
server/config.go

It is using the config option to set the timeout for access log streams.
The default duration is changed from 10 minutes to 1 minute. This makes sense to me since terminating connection sooner does little harm when the traffic is low while it enables load balancing more efficiently when traffic is high.
-golib dependencies is changed to the latest.
close #77

added timeout for access log streams

---

go.sum
server/authorization.go
server/authorization_test.go
server/config.go
server/config_test.go

close #9 
- yaml and json annotations for the `jwtProviderKey` field are added.
- The behavior does not change with unset (default option) `jwtProviderKey`.
- Tests are added with a more real `jwtClaims` and commented lines got removed.

enabled jwtProviderKey option

---

kokoro/scripts/integration_test_hybrid.sh

added back `buildDockerImages` which was accidentally removed during troubleshooting early on.

added gcloud build

---

kokoro/scripts/lib.sh

This is a quick fix for the integration test where the new configurations failed to be created.

deleting existing sample directory

---

main.go
server/config.go
server/config_test.go
server/handler.go
server/handler_test.go

In this version, I introduced the `Analytics.Credentials *google.Credentials` in addition to `Analytics.CredentialsJSON []byte`. And `Credentials` will be loaded from config, given path or application default credentials during the config loading and validation process. As a result, the `NewHandler()` method can unambiguously decide how to construct an analytics http client .
What is left to be addressed is that `Load()` method is also called by -cli during provisioning or other commands. When users intend to use ADC to authorize the adapter, they may still run CLI in a different environment lacking such credentials. We may need to introduce another argument to the `Load()` method to indicate whether it is invoked by CLI and allow validation of a config lacking explicit credentials.
This …

changes to config loading and validation to better support application default credentials

---

.github/workflows/docker.yaml

see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

github action update

---

server/config.go

to fix https://github.com/apigee/apigee-remote-service-cli/issues/110

default JWTProviderKey to empty string

---

server/authmanager.go
server/config.go

This is regarding: https://github.com/apigee/apigee-remote-service-cli/issues/121
It's to reuse this `LoadPrivateKey` method to load the key from the retrieved propertyset during provision.

exporting LoadPrivateKey for -cli to use

---

go.mod
go.sum
kokoro/README.md
kokoro/gcp_ubuntu/cgsaas_build.sh
kokoro/gcp_ubuntu/hybrid.cfg
kokoro/gcp_ubuntu/hybrid_build.sh
kokoro/gcp_ubuntu/loadtest_build.sh
kokoro/gcp_ubuntu/opdk_build.sh
kokoro/payloads/hybrid_app.json
kokoro/payloads/hybrid_product.json
kokoro/payloads/opgrp_product.json
kokoro/scripts/init.sh
kokoro/scripts/integration_test_cgsaas.sh
kokoro/scripts/integration_test_hybrid.sh
kokoro/scripts/integration_test_opdk.sh
kokoro/scripts/lib.sh
kokoro/scripts/load_test.sh

related to #93 
* Quota tests now check the last status code from the loop and verify the quota depletion. This eliminates spurious errors from the case where the quota bucket incidentally recovers right after its depletion and returns unexpected status code.
* Added tests on API product with OperationGroup. The quota identifier issue remains to be resolved: https://github.com/apigee/apigee-remote-service-golib/issues/34
* Test scripts and Kokoro build scripts are further separated so that the test scripts can be better run locally without additional tweaks provided necessary environment variables.

added operationgroup tests; eliminated spurious errors from quotas

---

integration-test/README.md
integration-test/scripts/init.sh
integration-test/scripts/lib.sh

This is still related to issue #134 
It will make the script cleaner by moving the prerequisite installation internal as we don't need to install them every time locally.

removed prerequisite installation

---

.github/workflows/docker.yaml
Dockerfile

updated goboring version
distroless/static for default (13m -> 6m)
distroless/base for goboring (50m -> 14m, more secure)

update docker build

---

go.mod
go.sum
server/accesslog.go
server/authorization.go
server/authorization_test.go
server/config.go
server/handler.go
server/handler_test.go
server/header_context.go
server/header_context_test.go

accepts `"*"` as `tenant.env_name` to put it multitenant mode
requires change: https://github.com/apigee/apigee-remote-service-cli/issues/149
For multitenant, Envoy configuration requires the addition of a segment like this to Envoy's `virtual_host` or `route` to specify an environment for ext_authz:
```
typed_per_filter_config:
envoy.filters.http.ext_authz:
"@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
check_settings:
context_extensions:
apigee_environment: test
```

multitenant env support

---

server/config.go
server/handler.go
server/handler_test.go

- OPDK only for analytics
- All Apigee platforms for other remote-service endpoints
Analytics mTLS is configured in `server.Config.Analytics.TLS`.
Others is configured in `server.Config.Tenant.TLS` - `AllowUnverifiedSSLCert` is also moved inside.

added mtls support

---

.github/workflows/build.yaml

In the Lint workflow of GitHub Actions, reviewdog has been complaining a few issues that shouldn't be there for go1.16

set up go1.16 before golangci-lint

---

config/config.go

Target is just a static header to be appended to requests via HTTP headers. While useful, it makes more sense to support this via generic HTTP header modification.

Replace Target with generic request header transformation

---

config/config.go

API Product matching requires an `api_source`. This is currently done using the hostname of the incoming request, however the new Proxy configuration is already associated with an API Proxy, which is semantically the same as `api_source`. This change adds a field to `ProxyConfig` to support this use case.

Fix up new Environment configuration schema

---

config/config.go
config/config_test.go

close #243 
Note one needs to explicitly set `--config/-c ""` to pass an empty config file path and skip the file loading. The default flag value has been `config.yaml` and should be backward compatible.

no config file is required

---

config/env_spec_ext_test.go
config/env_spec_request.go
config/env_spec_request_test.go
config/env_spec_test.go

If there are no operations for an api, assume a "match all" operation

---

config/env_spec.go
config/env_spec_ext_test.go
config/env_spec_request.go
config/env_spec_request_test.go
config/env_spec_test.go

Any intersection between the allowed JWT audiences and the aud in the claim will be acceptable.
Fix #301

"Any" semantics for allowed JWT audiences.

---

server/authorization.go
server/authorization_test.go

Cherrypick for 2.0.x line to address: https://github.com/apigee/apigee-remote-service-envoy/issues/320

fix AX sending issue

---

Dockerfile

ensure ca-certificates.crt is read only

---

config/env_spec_request.go
config/env_spec_request_test.go

Append "/" if `opPath` has no "/" as prefix.

---

Dockerfile

Fixes #325 in 2.0.x branch (cherry pick)

ensure ca-certificates.crt is read only (#326)

---

config/env_spec.go
config/env_spec_test.go
go.mod
server/authorization.go
server/authorization_test.go
server/header_context.go
server/header_context_test.go

* In order to avoid passing yet more arguments into apigeeDynamicDataHeaders(),
replace the `basepath` arg with the APISpec as a whole, so that we can pull
whatever other data we need out of it as we go on.
Closes #357

Add RevisionID to APISpec

---

server/accesslog.go
server/accesslog_test.go

The `:5001/metrics` return will have this:
```
proxy_latencies_bucket{method="GET",le="1"} 0
proxy_latencies_bucket{method="GET",le="2"} 1
proxy_latencies_bucket{method="GET",le="5"} 2
proxy_latencies_bucket{method="GET",le="10"} 2
proxy_latencies_bucket{method="GET",le="25"} 2
proxy_latencies_bucket{method="GET",le="50"} 2
proxy_latencies_bucket{method="GET",le="75"} 2
proxy_latencies_bucket{method="GET",le="100"} 2
proxy_latencies_bucket{method="GET",le="250"} 2
proxy_latencies_bucket{method="GET",le="500"} 2
proxy_latencies_bucket{method="GET",le="750"} 2
proxy_latencies_bucket{method="GET",le="1000"} 2
proxy_latencies_bucket{method="GET",le="2500"} 2
proxy_latencies_bucket{method="GET",le="5000"} 2
proxy_latencies_bucket{method="GET",le="7500"} 2 …
```

add monitoring related metrics

---

server/accesslog.go
server/accesslog_test.go

Sorry...but I realize `proxy_name` is also a necessary label for the metrics to work.

add proxy_name as label

---

server/accesslog.go

The label that Apigee uses should be `fault_source` instead of `fault_src`.

fix incorrect label name

---

Dockerfile_releaser
config/env_spec_request.go
config/env_spec_request_test.go
fault/fault.go
fault/fault_codes.go
fault/fault_test.go
server/authorization.go
server/authorization_test.go

https://github.com/apigee/apigee-remote-service-envoy/issues/371
Adding x-apigee-fault-code values for key management and JWT based authn and authz as well as other internal errors for ARC.
Notes:
- We cannot get more fine-grained fault-codes for key management yet because of how MP communicates the errors. MP only says [invalid apikey](https://github.com/apigee/apigee-remote-service-cli/blob/master/cmd/provision/proxies/remote-service-gcp/apiproxy/policies/Raise-Fault-Invalid-API-Key.xml). We need to either expand the existing handler or wait for the ACMS apis for getting more details, both of which are beyond the scope of this PR.
- Adding a `default` case to the Key management error `switch-case` as per discussion with @emschwar to ensure new errors in future get handled more …

Update Apigee Fault Codes for ARC

---

fault/fault_codes.go
server/authorization.go
server/authorization_test.go

We did not separate missing operation from missing API proxy, but it's useful to distinguish these cases.
Ref: #378

Add fault code for missing operation error

---

fault/fault_codes.go
server/header_context_test.go

* apiProxy.InternalError => environment.InternalError
This reflects that the ultimate source of the error is not the proxy,
but the environment its config runs in.
Closes: #384

Update fault codes
